FROM python:3.10-slim

WORKDIR /app

# Installation des dépendances
COPY requirements-streamlit.txt .
RUN pip install --no-cache-dir -r requirements-streamlit.txt

# Copie du script Streamlit
COPY ./app/services/app.py ./app.py

EXPOSE 8501

# Commande de lancement Streamlit configurée pour Cloud Run
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]